name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
      - name: Install dependencies
        run: rye sync
      - name: Run lint
        run: |
          rye run -- ruff check --output-format=github src/
          rye run -- ruff format --check src/
